// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonClickMe = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_ButtonClickMe, 223);
    lv_obj_set_height(ui_ButtonClickMe, 105);
    lv_obj_set_x(ui_ButtonClickMe, 4);
    lv_obj_set_y(ui_ButtonClickMe, -37);
    lv_obj_set_align(ui_ButtonClickMe, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonClickMe, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonClickMe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelClickMe = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_LabelClickMe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClickMe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelClickMe, 2);
    lv_obj_set_y(ui_LabelClickMe, -35);
    lv_obj_set_align(ui_LabelClickMe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelClickMe, "ClickMe!");

    ui_SliderTest = lv_slider_create(ui_HomeScreen);
    lv_slider_set_value(ui_SliderTest, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderTest) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderTest, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderTest, 237);
    lv_obj_set_height(ui_SliderTest, 10);
    lv_obj_set_x(ui_SliderTest, 3);
    lv_obj_set_y(ui_SliderTest, 44);
    lv_obj_set_align(ui_SliderTest, LV_ALIGN_CENTER);


    lv_obj_add_event_cb(ui_ButtonClickMe, ui_event_ButtonClickMe, LV_EVENT_ALL, NULL);
    uic_ButtonClickMe = ui_ButtonClickMe;

}
